const tmp = {
    state: {
        datalist: [
            {
              _id: "5f51167b2e8802c11e5ba781",
              imgUrl: "http://www.coman.icu/img/beauty/1.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
            {
              _id: "5f51167b2e8802c11e5ba782",
              imgUrl: "http://www.coman.icu/img/beauty/2.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba783",
              imgUrl: "http://www.coman.icu/img/beauty/3.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba784",
              imgUrl: "http://www.coman.icu/img/beauty/4.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba785",
              imgUrl: "http://www.coman.icu/img/beauty/5.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba786",
              imgUrl: "http://www.coman.icu/img/beauty/6.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba787",
              imgUrl: "http://www.coman.icu/img/beauty/7.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba788",
              imgUrl: "http://www.coman.icu/img/beauty/8.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba789",
              imgUrl: "http://www.coman.icu/img/beauty/9.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba7810",
              imgUrl: "http://www.coman.icu/img/beauty/10.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba7811",
              imgUrl: "http://www.coman.icu/img/beauty/11.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba7812",
              imgUrl: "http://www.coman.icu/img/beauty/12.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba7813",
              imgUrl: "http://www.coman.icu/img/beauty/13.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
                    {
              _id: "5f51167b2e8802c11e5ba7814",
              imgUrl: "http://www.coman.icu/img/beauty/14.jpg",
              three_subtit: "瑞士KOSSME鎏金奢享礼盒",
              price: 699,
              comment: 0,
              rest: 264,
              tag: "beauty",
            },
          ],
    },
    getters: {

    },
    mutations: {

    }
}

export default tmp;